export type VolumeUnit =
  | "Cubic Meter"
  | "Cubic Kilometer"
  | "Cubic Centimeter"
  | "Cubic Millimeter"
  | "Cubic Micrometer"
  | "Cubic Mile"
  | "Cubic Yard"
  | "Cubic Foot"
  | "Cubic Inch"
  | "Liter"
  | "Milliliter"
  | "Hectoliter"
  | "Centiliter"
  | "Deciliter"
  | "Megaliter"
  | "Microliter"
  | "Nanoliter"
  | "Picoliter"
  | "Acre-Foot"
  | "Board Foot"
  | "Bushel"
  | "Dram"
  | "Fluid Ounce"
  | "Gallon"
  | "Quart"
  | "Pint"
  | "Cup"
  | "Tablespoon"
  | "Teaspoon"
  | "Oil Barrel"
  | "Beer Barrel"
  | "Register Ton"
  | "Metric Cup";
